server:
  port: 8201 #指定运行端口
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
knife4j:
  gateway:
    enabled: true
    strategy: discover #网关文档聚合方式：服务发现（自动聚合）
    discover:
      version: openapi3 #配置OpenAPI3规范
      enabled: true #配置开启服务发现
    tags-sorter: order #配置tag排序规则
    operations-sorter: order #配置operation排序规则